

services:
  sistema-core:
    build: ./sistema-core
    ports:
      - "8080:8080"
    env_file:
      - .env

  ibanking:
    build: ./ibanking
    ports:
      - "5000:5000"
    env_file:
      - .env

  app-mobile:
    build: ./app-mobile
    ports:
      - "3000:3000"
    env_file:
      - .env

  portal-web:
    build: ./portal-web
    ports:
      - "80:80"
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sistema-core
      - ibanking
      - app-mobile
      - portal-web
